rango/urls.py
from django.urls import path
from rango import views
from rango.views import AboutView, add_category, show_category

app_name="rango"

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('forum/', views.forum, name='forum'),

    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('category/<slug:category_name_slug>/add_video/', views.add_video, name='add_video'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    
    path('add_category/<course_id>', views.add_category, name='add_category'),
    path('add_comment/<slug:category_name_slug>/', views.add_comment, name='add_comment'),
    
    path('courses/', views.courses, name='courses'),
    path('courses/<course_id>/', views.single_course, name='single_course'),
    path('courses/<course_id>/<slug:category_name_slug>/', views.single_category, name='single_category'),
    
    path('register_profile/', views.register_profile, name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('restricted/', views.restricted, name='restricted'),

    path('search/', views.search, name='search'),

    # lyy test:
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
]

tango_with_django_project/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView 
from django.urls import reverse

class MyRegistrationView(RegistrationView): 
     def get_success_url(self, user):
          return reverse('rango:register_profile')

urlpatterns = [
    path('', views.index, name='index'), # (url pattern, function to call, shortname of view) 
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    
    # lyy test:
    path('stock/', include('rango.urls')),

    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/forms.py
from django import forms
from rango.models import Page,Video
from rango.models import Category, Comment
from django.contrib.auth.models import User
from rango.models import UserProfile


class CategoryForm(forms.ModelForm): # inherit from django built-in form
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (don't include the category field).
        #fields = ('title', 'url', 'views')
    
    # overriding clean() method to validate user input
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # pure logical truthify
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        
        return cleaned_data

class VideoForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,
                            help_text="Please enter the title of the Video.")
    url = forms.URLField(max_length=200,
                        help_text="Please enter the URL of the Video.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Video
        exclude = ('category', )
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data


# for registration form
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

class CommentForm(forms.ModelForm):
    content = forms.CharField(max_length=500)
    class Meta:
        model = Comment
        fields = ('content',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template.defaultfilters import slugify
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from datetime import datetime

from rango.models import Page, Category, Comment, Course
from rango.forms import PageForm, CategoryForm, VideoForm
from rango.forms import UserForm, UserProfileForm, CommentForm
from django.views import View

from django.utils.decorators import method_decorator
from django.contrib.auth.models import User 
from rango.models import UserProfile

import json 
import requests
from rango.bing_search import run_query

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

# Updated the function definition
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    # If it's been more than a day since the last visit...
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        # Update the last visit cookie now that we have updated the count
        request.session['last_visit'] = str(datetime.now())
    else:
        # Set the last visit cookie
        request.session['last_visit'] = last_visit_cookie
    
    # Update/set the visits cookie
    request.session['visits'] = visits

# Create your views here.
def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    course_list = Course.objects.all()[:3]
    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!', # chapter 3 output
        'categories' : category_list,
        'pages': page_list,
        'courses': course_list
        # 'visits': int(request.COOKIES.get('visits', '1'))
    }
    
    visitor_cookie_handler(request)
    # context_dict['visits'] = request.session['visits']

    response =  render(request, 'rango/index.html', context_dict)
    return response

def about(request):
    # # c10
    # request.session.set_test_cookie()
    # if (request.session.test_cookie_worked()):
    #     print("TEST COOKIE WORKED!")
    #     request.session.delete_test_cookie()

    # c10 exercise
    visitor_cookie_handler(request)
    context_dict = {'visits': request.session['visits']}
    return render(request, 'rango/about.html', context_dict)

def forum(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {
        'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!', # chapter 3 output
        'categories' : category_list,
        'pages': page_list,
        # 'visits': int(request.COOKIES.get('visits', '1'))
    }
    return render(request, 'rango/forum.html', context_dict)

def courses(request):

    courses = Course.objects.all()
    context_dict = {
        'courses': courses,
    }

    return render(request, 'rango/courses.html', context_dict)

def single_course(request, course_id):
    this_course = Course.objects.filter(course_id=course_id)[0]
    topic_list = Category.objects.filter(course=this_course)
    context_dict = {
        'course': this_course,
        'topics': topic_list,
    }
    return render(request, 'rango/course.html', context_dict)

def single_category(request, course_id, category_name_slug):
    course = Course.objects.get(course_id=course_id)
    context_dict = {}
    context_dict['course'] = course

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    form = CommentForm()
    context_dict['form'] = form

    if request.method == 'POST':
        add_comment(request, category_name_slug)
    
    try:
        comment = Comment.objects.filter(category=category_name_slug).order_by('-posttime')[:6]
        context_dict['comments'] = comment
    except Comment.DoesNotExist:
        context_dict['comments'] = None
    return render(request, 'rango/single_category.html', context_dict)

def show_category(request, category_name_slug):
    context_dict= {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    form = CommentForm()
    context_dict['form'] = form

    # to add    
    try:
        comment = Comment.objects.filter(category=category_name_slug).order_by('-posttime')[:6]
        context_dict['comments'] = comment
    except Comment.DoesNotExist:
        context_dict['comments'] = None
    
    return render(request, 'rango/category.html', context=context_dict)
# to add
def add_comment(request, category_name_slug):
    form = CommentForm(request.POST)
    if form.is_valid() and form['content'] != None:
        f = form.save(commit=False)
        f.username = get_server_side_cookie(request, 'username', 'Anonym')
        f.username = request.user.username # temporary solution for comment username
        f.posttime = datetime.now()
        f.category = category_name_slug
        f.save()
        # to add
        return redirect(f'/stock/category/{category_name_slug}')
        # for redirect back to single_category
        # category = Category.objects.get(slug=category_name_slug)
        # return redirect(reverse('rango:single_category', 
        #     kwargs={'course_id': category.course.course_id,
        #             'category_name_slug': category_name_slug,
        #     }
        # ))
    else:
        print(form.errors)

@login_required
def add_video(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    
    if category is None:
        return redirect(reverse('rango:index'))
    
    form = VideoForm()

    if request.method == 'POST':
        form = VideoForm(request.POST)

        if form.is_valid():
            if category:
                video = form.save(commit=False)
                video.category = category
                video.views = 0
                video.save()

                return redirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_video.html', context=context_dict)


@login_required
def add_category(request, course_id):
    ## C9 exercise redirect:
    # if not request.user.is_authenticated:
        # return redirect(reverse('rango:login'))
    try:
        course = Course.objects.get(course_id=course_id)
    except Category.DoesNotExist:
        course = None
    
    if course is None:
        return redirect(reverse('rango:index'))
    
    form = CategoryForm()
    
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            this_category = form.save(commit=False)
            this_category.course = course
            this_category.views = 0
            this_category.likes = 0
            this_category.save()
            print(this_category)
            # Now that the category is saved, we could confirm this.
            # For now, just redirect the user back to the index view.
            return redirect('rango:single_course', course.course_id)
        else:
            # The supplied form contained errors -
            # just print them to the terminal.
            print(form.errors)
    # Will handle the bad form, new form, or no form supplied cases.
    # Render the form with error messages (if any).
    context_dict = {
        'form': form,
        'course': course,
    }
    return render(request, 'rango/add_category.html', context_dict)

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None # for exercise answer: what if the category does not exist handling
    
    # you cannot add a page to a Category that does not exist
    if category is None:
        return redirect('/rango/')
    
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()

                # for redirecting back to the single_category view
                course_id = page.category.course.course_id
                return redirect(reverse('rango:single_category', 
                    kwargs={'course_id': course_id,
                            'category_name_slug': category_name_slug,
                    }
                ))
        else:
            print(form.errors)

    # closing the func
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

@login_required

templates/rango/add_video.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
    <h1>Add a Page to {{ category.name }}</h1>
    <div>
        <!--'post' http submit the form-->
        <form id="add_video_form" method="post" action="/rango/category/{{ category.slug }}/add_video/">
            {% csrf_token %}
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Add Video" />
        </form>
    </div>
{% endblock %}

templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
            </li>
        {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
            </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
    <h1>You've added a category to course {{ course.course_id }}</h1>
{% endblock %}

{% block body_block %}
    <ul class="nav flex-column">

    
<!--show some trending pages-->
<div class="container-fluid">
    {% if category %}
        <h1>{{ category.name }}</h1>
        
        <!--C17 like button-->
        <div>
            <strong id="like_count">{{ category.likes }}</strong> likes
            {% if user.is_authenticated %}
            <button id="like_btn"
                    data-categoryid="{{ category.id }}"
                    class="btn btn-primary btn-sm"
                    type="button">
                <span data-feather="thumbs-up"></span>
                Like Category
            </button>
            {% endif %}
        </div>
            

        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}

        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
        {% endif %}
        
    {% else %}
        The specified category does not exist!
    {% endif %}
</div>
    <div >
        {% if comments %}
            {% for comment in comments %}
                <div class="media" id="comment-post">
                    <img id="comment-profile" class="mr-3" src="{% static 'images/profile.jpg' %}" alt="Generic placeholder image">
                    <div class="media-body">
                        <div class="row">
                            <div class="col">
                                <h5 class="mt-0">{{ comment.username }}</h5>
                            </div>
                            <div class="col">
                                @ {{ comment.posttime }}
                            </div>
                        </div>
                        {{ comment.content }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% if user.is_authenticated %}
    <form id="comment_form" method="post" action="{% url 'rango:add_comment' category.slug%}">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}
        {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Add Comment" />
    </form>
{% endif %}
    
{% endblock %}

templates/rango/category_list.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
            <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
            </li>
        {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
            </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

templates/rango/course_list.html
<ul class="nav flex-column">
    {% if course_list %}
        {% for course in course_list %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:single_course' course.course_id %}">
                <span data-feather="book"></span>{{ course.course_name }}
            </a>
            </li>
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

templates/rango/courses.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}

{% block body_block %}
<div class="container-fluid padding">
    <div class="row welcome text-center">
        <div class="col-12">
            <h3 class="display-4">Course On Offer</h3>
        </div>
    </div>
</div>
<hr>
<div class="container-fluid padding">
<div class="card-columns">
{% if courses %}
    {% for course in courses %}
        <!--assign each course a card view-->
        <!-- <div class="col-lg"> -->
            <div class="card bg-warning" id="course-card">
                <div class="card-header">
                    {{ course.course_id|upper }}
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{ course.course_name }}</h5>
                    <p class="card-text d-sm-none d-md-block">{{ course.course_description }}</p>
                </div>
                <div class="card-footer bg-success">
                    <a href="{% url 'rango:single_course' course.course_id %}" id="promote">details >></a>
                </div>
            </div>
        <!-- </div> -->
    {% endfor %}
{% endif %}
</div>
{% endblock body_block %}
    

templates/rango/forum.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load rango_template_tags %}


{% block title_block %}
    Tutorials
{% endblock title_block %}
    

{% block body_block %}
<!-- main frame -->
<div class="container-fluid">
<div class="row">
    <!-- sidebar content -->
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
            {% get_category_list category %}
        </div>
    </nav>
    
    <!--main body-->
    <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">	
        <h1>
            <div class="jumbotron p-4">
                <div class="container">
                    <h1 class="jumbotron-heading">Rango says...</h1>
                    <div>
                        <h2 class="h2">
                        {% if user.is_authenticated %}
                            howdy {{ user.username }}!
                        {% else %}
                            Rango says hey there partner!
                        {% endif %}
                        </h2>
                    <strong>{{ boldmessage }}</strong>
                    </div>
                </div>
            </div>
                
        </h1>
        <div>
            <strong>{{ boldmessage }}</strong><br />
        </div>
    
        <!--chapter6 added categories variable-->
        {% if  categories %}
        <h2>Most Liked Categories</h2>
        <ul>
            {% for category in categories %}
                <!-- missing '/' in the end of href caused a problem-->
                <!-- li markup has to be in one line to pass the test-->
                <li><a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
    
    
        {% if pages %} <!--TwD C6 Exercise No.2 test-->
        <h2>Most Viewed Pages</h2>
        <ul>
            
            {% for page in pages %}
            <!-- li markup has to be in one line to pass the test-->
            <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}      
        </ul>
        {% else %}
        <strong>There are no pages present.</strong>
        {% endif %}
    
    
        <div>
            <!--not deleting comments result in c9 test failed-->
            <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        </div>
    </main>
</div>
</div>
{% endblock body_block %}

templates/rango/original_about.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
        <title>Rango says here is the about page.</title>
    </head>

    <body>
        <h1>This tutorial has been put together</h1>
        <img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
        <img src="{{MEDIA_URL}}cat.jpg" alt="Picture of a Cat." /> <!--remove the #-->
        <a href='/rango/'>Index</a>
    </body>
</html>

templates/rango/original_add_category.html
<!DOCTYPE html>
    <html>
        <head>
            <title>Rango</title>
        </head>
        <body>
            <h1>Add a Category</h1>
            <div>
                <!--'post' http submit the form-->
                <form id="category_form" method="post" action="/rango/add_category/">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}
                        {{ field }}
                    {% endfor %}
                    <input type="submit" name="submit" value="Create Category" />
                </form>
            </div>
        </body>
</html>

templates/rango/original_add_page.html
<!DOCTYPE html>
    <html>
        <head>
            <title>Rango</title>
        </head>
        <body>
            <h1>Add a Page to {{ category.name }}</h1>
            <div>
                <!--'post' http submit the form-->
                <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
                    {% csrf_token %}
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}
                        {{ field }}
                    {% endfor %}
                    <input type="submit" name="submit" value="Add Page" />
                </form>
            </div>
        </body>
</html>

templates/rango/original_base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock title_block %}
        </title>
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
    </head>
    <body>
        <!-- Page specific content goes here -->
        <div>
            {% block body_block %}
            <!--This is body_block's default content.-->
            {% endblock body_block%}
        </div>

        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'rango:logout' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            {% else %}
                <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
                <li><a href="{% url 'rango:login' %}">Login</a></li>
            {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>    
    </body>
</html>

templates/rango/original_category.html
<!DOCTYPE html>
<html>
    <head>
        <title>Rango</title>
    </head>

    <body>
        <div>
        {% if category %}
            <h1>{{ category.name }}</h1>
            {% if pages %}
            <ul>
                {% for page in pages %}
                <li>
                    <a href="{{ page.url }}">{{ page.title }}</a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <strong>No pages currently in category.</strong>
            {% endif %}

            <!--C7 exercise: make sure add page link only exists when category exists-->
            <a href="/rango/category/{{ category.slug }}/add_page/">Add Page</a><br />
        {% else %}
            The specified category does not exist!
        {% endif %}

        <a href="/rango/">Index</a> <!--C6 exerciese 4-->
        </div>
    </body>
    
</html>

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %} 
    Register - Step 2
{% endblock %}

{% block body_block %}
<hr>
<div class="container-fluid padding">
<div class="row align-items-center">
    <div class="col"></div>
    <div class="col">
        <div class="container-fluid padding">
            <h3>Step 2 - Add a Profile</h3>

            <form method="post"
            action="{% url 'rango:register_profile' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Create Profile" />
            </form>
        </div>
    </div>
    <div class="col"></div>
</div>
</div>
{%endblock%}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>Register for Rango</h1>
    
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
    {% else %}
        Rango says: <strong>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- Display each form-->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}